services:
  web:
    container_name: govuk-frontend-flask
    build:
      context: .
      args:
        REQUIREMENTS: requirements_development.txt
    restart: always
    environment:
      - CONTACT_EMAIL=[contact email]
      - CONTACT_PHONE=[contact phone]
      - DEPARTMENT_NAME=[name of department]
      - DEPARTMENT_URL=[url of department]
      - SECRET_KEY=CHANGE_ME
      - SERVICE_NAME=[name of service]
      - SERVICE_PHASE=[phase]
      - SERVICE_URL=[url of service]
    ports:
      - "8000:8000"
#    volumes:
#      - .:/home/app/access
  