services:
  web:
    container_name: govuk-frontend-flask
    build:
      context: .
      args:
        BASE_IMAGE: python:3.12-bookworm
      target: development
    restart: always
    environment:
      - SECRET_KEY=CHANGE_ME
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app/access
  