services:
  web:
    container_name: govuk-frontend-flask
    build:
      context: .
      args:
        BASE_IMAGE: python:3.12-bookworm
        REQUIREMENTS_FILE: "requirements-development.txt"
      target: development
    restart: always
    environment:
      - SECRET_KEY=CHANGE_ME
      - MAINTENANCE_MODE=FALSE
      - FLASK_RUN_PORT=8020
      - SENTRY_DSN=${SENTRY_DSN:-}
    ports:
      - "8020:8020"
    volumes:
      - ./app:/home/app/access/app
  