services:
  web:
    container_name: govuk-frontend-flask
    build:
      context: .
      args:
        REQUIREMENTS: requirements_development.txt
        BASE_IMAGE: python:3.12-bookworm
      target: development
    restart: always
    environment:
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - CONTACT_PHONE=${CONTACT_PHONE}
      - DEPARTMENT_NAME=${DEPARTMENT_NAME}
      - DEPARTMENT_URL=${DEPARTMENT_URL}
      - SECRET_KEY=CHANGE_ME
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app/access
  