services:
  watcher:
    container_name: watcher
    build:
      dockerfile: node.Dockerfile
      context: .
    restart: always
    volumes:
      - ./app/static:/home/node/app/static

  web:
    container_name: govuk-frontend-flask
    build:
      context: .
      args:
        BASE_IMAGE: python:3.13-bookworm
        REQUIREMENTS_FILE: "requirements-development.txt"
      target: development
    restart: always
    environment:
      - CLA_BACKEND_URL=http://host.docker.internal:8010
      - SECRET_KEY=CHANGE_ME
      - MAINTENANCE_MODE=FALSE
      - FLASK_RUN_PORT=8020
      - SENTRY_DSN=${SENTRY_DSN:-}
      - GOVUK_NOTIFY_API_KEY=${GOVUK_NOTIFY_API_KEY:-}
      - EMAIL_ORCHESTRATOR_URL=${EMAIL_ORCHESTRATOR_URL:-}
    ports:
      - "8020:8020"
    volumes:
      - ./app:/home/app/access/app
      - ./tests:/home/app/access/tests
