from flask_babel import lazy_gettext as _
import os

ADAPTATION_LANGUAGES = [
    ("ASSAMESE", "Assamese"),
    ("AZERI", "Azeri"),
    ("AFRIKAANS", "Afrikaans"),
    ("ALGERIAN", "Algerian"),
    ("ASHANTI", "Ashanti"),
    ("AKAN", "Akan"),
    ("ALBANIAN", "Albanian"),
    ("AMHARIC", "Amharic"),
    ("ARMENIAN", "Armenian"),
    ("ARABIC", "Arabic"),
    ("ASSYRIAN", "Assyrian"),
    ("AZERBAIJANI", "Azerbaijani"),
    ("BADINI", "Badini"),
    ("BENGALI", "Bengali"),
    ("BURMESE", "Burmese"),
    ("BAJUNI", "Bajuni"),
    ("BELORUSSIAN", "Belorussian"),
    ("BOSNIAN", "Bosnian"),
    ("BERBER", "Berber"),
    ("BASQUE", "Basque"),
    ("BULGARIAN", "Bulgarian"),
    ("BRAVA", "Brava"),
    ("BRAZILIAN", "Brazilian"),
    ("CANTONESE", "Cantonese"),
    ("CEBUANO", "Cebuano"),
    ("CREOLE", "Creole"),
    ("CHINESE", "Chinese"),
    ("CHEROKEE", "Cherokee"),
    ("COLUMBIAN", "Columbian"),
    ("CAMBODIAN", "Cambodian"),
    ("CHAOCHOW", "Chaochow"),
    ("CROATIAN", "Croatian"),
    ("CATALAN", "Catalan"),
    ("CZECH", "Czech"),
    ("DANISH", "Danish"),
    ("DARI", "Dari"),
    ("DUTCH", "Dutch"),
    ("EGYPTIAN", "Egyptian"),
    ("ENGLISH", "English"),
    ("ESTONIAN", "Estonian"),
    ("ERITREAN", "Eritrean"),
    ("ESPERANTO", "Esperanto"),
    ("ETHIOPIAN", "Ethiopian"),
    ("FARSI", "Farsi"),
    ("FIJIAN", "Fijian"),
    ("FLEMISH", "Flemish"),
    ("FANTI", "Fanti"),
    ("FRENCH", "French"),
    ("FINNISH", "Finnish"),
    ("FULLA", "Fulla"),
    ("GA", "Ga"),
    ("GERMAN", "German"),
    ("GURMUKHI", "Gurmukhi"),
    ("GAELIC", "Gaelic"),
    ("GORANI", "Gorani"),
    ("GEORGIAN", "Georgian"),
    ("GREEK", "Greek"),
    ("GUJARATI", "Gujarati"),
    ("HAKKA", "Hakka"),
    ("HEBREW", "Hebrew"),
    ("HINDI", "Hindi"),
    ("HOMA", "Homa"),
    ("HAUSA", "Hausa"),
    ("HUNGARIAN", "Hungarian"),
    ("HUI", "Hui"),
    ("ICELANDIC", "Icelandic"),
    ("IGBO", "Igbo"),
    ("ILOCANO", "Ilocano"),
    ("INDONESIAN", "Indonesian"),
    ("IRAQI", "Iraqi"),
    ("IRANIAN", "Iranian"),
    ("ITALIAN", "Italian"),
    ("JAPANESE", "Japanese"),
    ("KASHMIRI", "Kashmiri"),
    ("KREO", "Kreo"),
    ("KIRUNDI", "Kirundi"),
    ("KURMANJI", "Kurmanji"),
    ("KANNADA", "Kannada"),
    ("KOREAN", "Korean"),
    ("KRIO", "Krio"),
    ("KOSOVAN", "Kosovan"),
    ("KURDISH", "Kurdish"),
    ("KINYARWANDA", "Kinyarwanda"),
    ("KINYAMIRENGE", "Kinyamirenge"),
    ("KAZAKH", "Kazakh"),
    ("LATVIAN", "Latvian"),
    ("LAOTIAN", "Laotian"),
    ("LAO", "Lao"),
    ("LUBWISI", "Lubwisi"),
    ("LEBANESE", "Lebanese"),
    ("LINGALA", "Lingala"),
    ("LUO", "Luo"),
    ("LUSOGA", "Lusoga"),
    ("LITHUANIAN", "Lithuanian"),
    ("LUGANDA", "Luganda"),
    ("MANDARIN", "Mandarin"),
    ("MACEDONIAN", "Macedonian"),
    ("MOLDOVAN", "Moldovan"),
    ("MIRPURI", "Mirpuri"),
    ("MANDINKA", "Mandinka"),
    ("MALAY", "Malay"),
    ("MONGOLIAN", "Mongolian"),
    ("MOROCCAN", "Moroccan"),
    ("MARATHI", "Marathi"),
    ("MALTESE", "Maltese"),
    ("MALAYALAM", "Malayalam"),
    ("NDEBELE", "Ndebele"),
    ("NEPALESE", "Nepalese"),
    ("NIGERIAN", "Nigerian"),
    ("NORWEGIAN", "Norwegian"),
    ("NYAKUSE", "Nyakuse"),
    ("OROMO", "Oromo"),
    ("OTHER", "Other"),
    ("PAHARI", "Pahari"),
    ("PERSIAN", "Persian"),
    ("PORTUGUESE", "Portuguese"),
    ("PHILIPINO", "Philipino"),
    ("POLISH", "Polish"),
    ("POTHWARI", "Pothwari"),
    ("PUSTHU", "Pusthu"),
    ("PUNJABI", "Punjabi"),
    ("ROMANIAN", "Romanian"),
    ("RUSSIAN", "Russian"),
    ("SOTHO", "Sotho"),
    ("SERBO-CROAT", "Serbo-Croat"),
    ("SWEDISH", "Swedish"),
    ("SERBIAN", "Serbian"),
    ("SHONA", "Shona"),
    ("SINHALESE", "Sinhalese"),
    ("SIRAIKI", "Siraiki"),
    ("SLOVAK", "Slovak"),
    ("SAMOAN", "Samoan"),
    ("SLOVENIAN", "Slovenian"),
    ("SOMALI", "Somali"),
    ("SORANI", "Sorani"),
    ("SPANISH", "Spanish"),
    ("SRI LANKAN", "Sri Lankan"),
    ("SCOTTISH GAELIC", "Scottish Gaelic"),
    ("SUDANESE", "Sudanese"),
    ("SWAHILI", "Swahili"),
    ("SWAHILLI", "Swahilli"),
    ("SYLHETI", "Sylheti"),
    ("TAMIL", "Tamil"),
    ("TIBETAN", "Tibetan"),
    ("TELEGU", "Telegu"),
    ("ELAKIL", "Elakil"),
    ("TAGALOG", "Tagalog"),
    ("THAI", "Thai"),
    ("TIGRINIAN", "Tigrinian"),
    ("TIGRE", "Tigre"),
    ("TAJIK", "Tajik"),
    ("TAIWANESE", "Taiwanese"),
    ("TURKMANISH", "Turkmanish"),
    ("TSWANA", "Tswana"),
    ("TURKISH", "Turkish"),
    ("TWI", "Twi"),
    ("UGANDAN", "Ugandan"),
    ("UKRANIAN", "Ukranian"),
    ("URDU", "Urdu"),
    ("USSIAN", "Ussian"),
    ("UZBEK", "Uzbek"),
    ("VIETNAMESE", "Vietnamese"),
    ("WELSH", "Welsh"),
    ("WOLOF", "Wolof"),
    ("XHOSA", "Xhosa"),
    ("YUGOSLAVIAN", "Yugoslavian"),
    ("YIDDISH", "Yiddish"),
    ("YORUBA", "Yoruba"),
    ("ZULU", "Zulu"),
]

LANG_CHOICES = [
    (lang_code.lower(), lang_name)
    for lang_code, lang_name in ADAPTATION_LANGUAGES
    if lang_code not in ("ENGLISH", "WELSH")
]

CONTACT_PREFERENCE = [
    ("call", "I will call you"),
    ("callback", "Call me back"),
    ("thirdparty", "Call someone else instead of me"),
]

# If there are no slots available for call me back this will show
NO_SLOT_CONTACT_PREFERENCE = [
    ("call", "I will call you"),
    ("thirdparty", "Call someone else instead of me"),
]

SELECT_OPTION_DEFAULT = [("", _("-- Please select --"))]
THIRDPARTY_RELATIONSHIP = [
    ("parent_guardian", "Parent or guardian"),
    ("family_friend", "Family member or friend"),
    ("professional", "Professional"),
    ("legal_advisor", "Legal adviser"),
    ("other", "Other"),
]
THIRDPARTY_RELATIONSHIP_CHOICES = SELECT_OPTION_DEFAULT + THIRDPARTY_RELATIONSHIP

GOVUK_NOTIFY_TEMPLATES = {
    "PUBLIC_CALLBACK_NOT_REQUESTED": {
        "en": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CALLBACK_NOT_REQUESTED",
            "382cc41c-b81d-4197-8819-2ad76522d03d",
        ),
        "cy": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CALLBACK_NOT_REQUESTED_WELSH",
            "5ae3e895-95f5-44bb-b7d0-0224273c908d",
        ),
    },
    "PUBLIC_CALLBACK_WITH_NUMBER": {
        "en": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CALLBACK_WITH_NUMBER",
            "b4cfa1b6-f1e9-44c1-9b02-f07ba896b669",
        ),
        "cy": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CALLBACK_WITH_NUMBER_WELSH",
            "7428dd15-8583-4e2d-9d0a-c8a4e0b740b4",
        ),
    },
    "PUBLIC_CALLBACK_WITH_NO_NUMBER": {
        "en": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CALLBACK_WITH_NO_NUMBER",
            "3e2926c5-1bdf-4eb3-b212-7f206f1d764d",
        ),
        "cy": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CALLBACK_WITH_NO_NUMBER_WELSH",
            "71f9343e-09c0-49d8-aee6-86ceec7fcda8",
        ),
    },
    "PUBLIC_CALLBACK_THIRD_PARTY": {
        "en": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CALLBACK_THIRD_PARTY",
            "7ffc6de3-07bd-4232-b416-cf18d0abfec6",
        ),
        "cy": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CALLBACK_THIRD_PARTY_WELSH",
            "23105d37-d59a-47a5-afdb-17a442cab3d8",
        ),
    },
    "PUBLIC_CONFIRMATION_NO_CALLBACK": {
        "en": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CONFIRMATION_NO_CALLBACK",
            "1a56ee47-a200-43f9-bab2-e0852da0714b",
        ),
        "cy": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CONFIRMATION_NO_CALLBACK_WELSH",
            "25237d11-a531-4aca-a482-d232c2cb47d4",
        ),
    },
    "PUBLIC_CONFIRMATION_EMAIL_CALLBACK_REQUESTED": {
        "en": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CONFIRMATION_EMAIL_CALLBACK_REQUESTED",
            "020ba10c-ac98-4b7c-a49f-1f129462506b",
        ),
        "cy": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CONFIRMATION_EMAIL_CALLBACK_REQUESTED_WELSH",
            "8b169ee3-4295-4a6b-beb3-ca67c8123e6b",
        ),
    },
    "PUBLIC_CONFIRMATION_EMAIL_CALLBACK_REQUESTED_THIRDPARTY": {
        "en": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CONFIRMATION_EMAIL_CALLBACK_REQUESTED_THIRDPARTY",
            "ca425753-c31b-426b-a532-b864701b2178",
        ),
        "cy": os.environ.get(
            "GOVUK_NOTIFY_TEMPLATE_PUBLIC_CONFIRMATION_EMAIL_CALLBACK_REQUESTED_THIRDPARTY_WELSH",
            "9fbf2cda-3097-4ce2-b6c2-371acf391698",
        ),
    },
}
