# Default values for cla-backend in the staging environment.
environment: "staging"

ingress:
  enabled: true
  hosts:
    - host: "access-civil-legal-aid-staging.cloud-platform.service.justice.gov.uk"
      paths:
        - path: /
          pathType: ImplementationSpecific

whitelist:
  enabled: false

envVars:
  CLA_BACKEND_URL:
    value: "http://cla-backend-app.laa-cla-backend-training.svc.cluster.local"