# Default values for cla-backend in the production environment.
environment: "production"

ingress:
  enabled: true
  host: "checklegalaid.service.gov.uk"
  tls:
    secretName: "tls-certificate"
  annotations:
    allow-duplicate-host: "true"
    nginx.ingress.kubernetes.io/canary: "true"
    allowed-duplicate-ns: "laa-cla-public-production,laa-access-civil-legal-aid-production"
whitelist:
  enabled: true

envVars:
  CLA_BACKEND_URL:
    value: "http://cla-backend-app.laa-cla-backend-production.svc.cluster.local"