# Default values for cla-backend in the production environment.
environment: "production"

ingress:
  enabled: true
  hosts:
    - host: "access-civil-legal-aid.cloud-platform.service.justice.gov.uk"
      paths:
        - path: /
          pathType: ImplementationSpecific