# Default values for cla-backend in the staging environment.
environment: "staging"

ingress:
  enabled: true
  hosts:
    - host: "access-civil-legal-aid-staging.cloud-platform.service.justice.gov.uk"
      paths:
        - path: /
          pathType: ImplementationSpecific

envVars:
  SECRET_KEY:
    secret:
      name: secret-key
      key: value
      optional: false