# Default values for laa-access-civil-legal-aid in the uat environment.
environment: "uat"

ingress:
  enabled: true
  hosts:
    - host: "access-civil-legal-aid-uat.cloud-platform.service.justice.gov.uk"
      paths:
        - path: /
          pathType: ImplementationSpecific

# Lists don't deep merge, so this list of envVars overrides anything defined in an earlier values file
envVars:
  DEBUG:
    value: "True"
