# Default values for laa-access-civil-legal-aid in the uat environment.
environment: "uat"

ingress:
  enabled: true
  hosts:
    - host: "access-civil-legal-aid-uat.cloud-platform.service.justice.gov.uk"
      paths:
        - path: /
          pathType: ImplementationSpecific
  annotations:
    allowed-duplicate-ns: "laa-cla-public-staging,laa-access-civil-legal-aid-uat"

whitelist:
  enabled: true

# Lists don't deep merge, so this list of envVars overrides anything defined in an earlier values file
envVars:
  DEBUG:
    value: "True"
  CLA_BACKEND_URL:
    value: "http://cla-backend-app.laa-cla-backend-uat.svc.cluster.local"