# Default values for cla-backend in the staging environment.
environment: "staging"

ingress:
  enabled: true
  host: "staging.checklegalaid.service.gov.uk"
  tls:
    secretName: "tls-certificate"
  annotations:
    allow-duplicate-host: "true"
    nginx.ingress.kubernetes.io/canary: "true"
    allowed-duplicate-ns: "laa-cla-public-staging,laa-access-civil-legal-aid-staging"

whitelist:
  enabled: true

envVars:
  CLA_BACKEND_URL:
    value: "http://cla-backend-app.laa-cla-backend-staging.svc.cluster.local"