# Host to use for canonical URL generation (without trailing slash)
host: https://ministryofjustice.github.io/laa-access-civil-legal-aid

# Header-related options
show_govuk_logo: true
service_name: Check if you can get legal aid docs
service_link: https://ministryofjustice.github.io/laa-access-civil-legal-aid
phase: Alpha

# Links to show on right-hand-side of header
header_links:
  Documentation: /
  GitHub: https://github.com/ministryofjustice/laa-access-civil-legal-aid

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: true

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 3

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: true
