from flask_babel import lazy_gettext as _

ADAPTATION_LANGUAGES = [
    ("", ""),
    ("ASSAMESE", "Assamese"),
    ("AZERI", "Azeri"),
    ("AFRIKAANS", "Afrikaans"),
    ("ALGERIAN", "Algerian"),
    ("ASHANTI", "Ashanti"),
    ("AKAN", "Akan"),
    ("ALBANIAN", "Albanian"),
    ("AMHARIC", "Amharic"),
    ("ARMENIAN", "Armenian"),
    ("ARABIC", "Arabic"),
    ("ASSYRIAN", "Assyrian"),
    ("AZERBAIJANI", "Azerbaijani"),
    ("BADINI", "Badini"),
    ("BENGALI", "Bengali"),
    ("BURMESE", "Burmese"),
    ("BAJUNI", "Bajuni"),
    ("BELORUSSIAN", "Belorussian"),
    ("BOSNIAN", "Bosnian"),
    ("BERBER", "Berber"),
    ("BASQUE", "Basque"),
    ("BULGARIAN", "Bulgarian"),
    ("BRAVA", "Brava"),
    ("BRAZILIAN", "Brazilian"),
    ("CANTONESE", "Cantonese"),
    ("CEBUANO", "Cebuano"),
    ("CREOLE", "Creole"),
    ("CHINESE", "Chinese"),
    ("CHEROKEE", "Cherokee"),
    ("COLUMBIAN", "Columbian"),
    ("CAMBODIAN", "Cambodian"),
    ("CHAOCHOW", "Chaochow"),
    ("CROATIAN", "Croatian"),
    ("CATALAN", "Catalan"),
    ("CZECH", "Czech"),
    ("DANISH", "Danish"),
    ("DARI", "Dari"),
    ("DUTCH", "Dutch"),
    ("EGYPTIAN", "Egyptian"),
    ("ENGLISH", "English"),
    ("ESTONIAN", "Estonian"),
    ("ERITREAN", "Eritrean"),
    ("ESPERANTO", "Esperanto"),
    ("ETHIOPIAN", "Ethiopian"),
    ("FARSI", "Farsi"),
    ("FIJIAN", "Fijian"),
    ("FLEMISH", "Flemish"),
    ("FANTI", "Fanti"),
    ("FRENCH", "French"),
    ("FINNISH", "Finnish"),
    ("FULLA", "Fulla"),
    ("GA", "Ga"),
    ("GERMAN", "German"),
    ("GURMUKHI", "Gurmukhi"),
    ("GAELIC", "Gaelic"),
    ("GORANI", "Gorani"),
    ("GEORGIAN", "Georgian"),
    ("GREEK", "Greek"),
    ("GUJARATI", "Gujarati"),
    ("HAKKA", "Hakka"),
    ("HEBREW", "Hebrew"),
    ("HINDI", "Hindi"),
    ("HOMA", "Homa"),
    ("HAUSA", "Hausa"),
    ("HUNGARIAN", "Hungarian"),
    ("HUI", "Hui"),
    ("ICELANDIC", "Icelandic"),
    ("IGBO", "Igbo"),
    ("ILOCANO", "Ilocano"),
    ("INDONESIAN", "Indonesian"),
    ("IRAQI", "Iraqi"),
    ("IRANIAN", "Iranian"),
    ("ITALIAN", "Italian"),
    ("JAPANESE", "Japanese"),
    ("KASHMIRI", "Kashmiri"),
    ("KREO", "Kreo"),
    ("KIRUNDI", "Kirundi"),
    ("KURMANJI", "Kurmanji"),
    ("KANNADA", "Kannada"),
    ("KOREAN", "Korean"),
    ("KRIO", "Krio"),
    ("KOSOVAN", "Kosovan"),
    ("KURDISH", "Kurdish"),
    ("KINYARWANDA", "Kinyarwanda"),
    ("KINYAMIRENGE", "Kinyamirenge"),
    ("KAZAKH", "Kazakh"),
    ("LATVIAN", "Latvian"),
    ("LAOTIAN", "Laotian"),
    ("LAO", "Lao"),
    ("LUBWISI", "Lubwisi"),
    ("LEBANESE", "Lebanese"),
    ("LINGALA", "Lingala"),
    ("LUO", "Luo"),
    ("LUSOGA", "Lusoga"),
    ("LITHUANIAN", "Lithuanian"),
    ("LUGANDA", "Luganda"),
    ("MANDARIN", "Mandarin"),
    ("MACEDONIAN", "Macedonian"),
    ("MOLDOVAN", "Moldovan"),
    ("MIRPURI", "Mirpuri"),
    ("MANDINKA", "Mandinka"),
    ("MALAY", "Malay"),
    ("MONGOLIAN", "Mongolian"),
    ("MOROCCAN", "Moroccan"),
    ("MARATHI", "Marathi"),
    ("MALTESE", "Maltese"),
    ("MALAYALAM", "Malayalam"),
    ("NDEBELE", "Ndebele"),
    ("NEPALESE", "Nepalese"),
    ("NIGERIAN", "Nigerian"),
    ("NORWEGIAN", "Norwegian"),
    ("NYAKUSE", "Nyakuse"),
    ("OROMO", "Oromo"),
    ("OTHER", "Other"),
    ("PAHARI", "Pahari"),
    ("PERSIAN", "Persian"),
    ("PORTUGUESE", "Portuguese"),
    ("PHILIPINO", "Philipino"),
    ("POLISH", "Polish"),
    ("POTHWARI", "Pothwari"),
    ("PUSTHU", "Pusthu"),
    ("PUNJABI", "Punjabi"),
    ("ROMANIAN", "Romanian"),
    ("RUSSIAN", "Russian"),
    ("SOTHO", "Sotho"),
    ("SERBO-CROAT", "Serbo-Croat"),
    ("SWEDISH", "Swedish"),
    ("SERBIAN", "Serbian"),
    ("SHONA", "Shona"),
    ("SINHALESE", "Sinhalese"),
    ("SIRAIKI", "Siraiki"),
    ("SLOVAK", "Slovak"),
    ("SAMOAN", "Samoan"),
    ("SLOVENIAN", "Slovenian"),
    ("SOMALI", "Somali"),
    ("SORANI", "Sorani"),
    ("SPANISH", "Spanish"),
    ("SRI LANKAN", "Sri Lankan"),
    ("SCOTTISH GAELIC", "Scottish Gaelic"),
    ("SUDANESE", "Sudanese"),
    ("SWAHILI", "Swahili"),
    ("SWAHILLI", "Swahilli"),
    ("SYLHETI", "Sylheti"),
    ("TAMIL", "Tamil"),
    ("TIBETAN", "Tibetan"),
    ("TELEGU", "Telegu"),
    ("ELAKIL", "Elakil"),
    ("TAGALOG", "Tagalog"),
    ("THAI", "Thai"),
    ("TIGRINIAN", "Tigrinian"),
    ("TIGRE", "Tigre"),
    ("TAJIK", "Tajik"),
    ("TAIWANESE", "Taiwanese"),
    ("TURKMANISH", "Turkmanish"),
    ("TSWANA", "Tswana"),
    ("TURKISH", "Turkish"),
    ("TWI", "Twi"),
    ("UGANDAN", "Ugandan"),
    ("UKRANIAN", "Ukranian"),
    ("URDU", "Urdu"),
    ("USSIAN", "Ussian"),
    ("UZBEK", "Uzbek"),
    ("VIETNAMESE", "Vietnamese"),
    ("WELSH", "Welsh"),
    ("WOLOF", "Wolof"),
    ("XHOSA", "Xhosa"),
    ("YUGOSLAVIAN", "Yugoslavian"),
    ("YIDDISH", "Yiddish"),
    ("YORUBA", "Yoruba"),
    ("ZULU", "Zulu"),
]

LANG_CHOICES = [
    (lang_code.lower(), lang_name)
    for lang_code, lang_name in ADAPTATION_LANGUAGES
    if lang_code not in ("ENGLISH", "WELSH")
]

CONTACT_PREFERENCE = [
    ("call", _("I will call you")),
    ("callback", _("Call me back")),
    ("thirdparty", _("Call someone else instead of me")),
]

# If there are no slots available for call me back this will show
NO_SLOT_CONTACT_PREFERENCE = [
    ("call", _("I will call you")),
    ("thirdparty", _("Call someone else instead of me")),
]

SELECT_OPTION_DEFAULT = [("", _("-- Please select --"))]
THIRDPARTY_RELATIONSHIP = [
    ("parent_guardian", _("Parent or guardian")),
    ("family_friend", _("Family member or friend")),
    ("professional", _("Professional")),
    ("legal_advisor", _("Legal adviser")),
    ("other", _("Other")),
]
THIRDPARTY_RELATIONSHIP_CHOICES = SELECT_OPTION_DEFAULT + THIRDPARTY_RELATIONSHIP
