# Default values for laa-access-civil-legal-aid.
# These can be overwritten by values defined in environment specific values files.
replicaCount: 1

image:
  repository: laa-access-civil-legal-aid
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  containerPort: 8000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # We already have a serviceaccount so we don't want to create another.
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "modsec"
  annotations:
    allow-duplicate-host: "true"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "0"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/canary-by-cookie: "canary"
    nginx.ingress.kubernetes.io/session-cookie-name: "ROUTE"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    nginx.ingress.kubernetes.io/session-cookie-refresh: "true"
    nginx.ingress.kubernetes.io/session-cookie-expires: "300"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "300"
  cluster:
    name: green
    weight: '100'
  tls: []

whitelist:
  enabled: true

resources: {}

autoscaling:
  enabled: false

volumes: []

volumeMounts: []
nodeSelector: {}

tolerations: []

affinity: {}

envVars:
  SECRET_KEY:
    secret:
      name: secret-key
      key: value
      optional: false
  SENTRY_DSN:
    secret:
      name: sentry
      key: dsn
  MAINTENANCE_MODE:
    configmap:
      name: maintenance-mode
      key: enabled
      optional: true
  RATELIMIT_ENABLED:
    configmap:
      name: ratelimit
      key: enabled
      optional: true

  OS_PLACES_API_KEY:
    secret:
      name: os-places
      key: key
  EMAIL_ORCHESTRATOR_URL:
    configmap:
      name: notify-orchestrator
      key: url
      optional: true