name: Build documentation

on:
  workflow_call:
    outputs:
      artifact-name:
        description: "GitHub Pages deployment artifact identifier"
        value: github-pages
      success:
        description: "Whether the build completed successfully"
        value: ${{ jobs.build.outputs.success }}

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:v3
    steps:
      # We only checkout the docs directory, which allows us to keep all necessary files for
      # generating the docs separate from the app.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            docs
          sparse-checkout-cone-mode: false
      # We move the docs directory to the root so it is treated as if the docs directory was
      # the only thing in the repository.
      - name: Move directory to root
        run: |
          mv docs/* .
          rm -rf docs
      - name: Compile Markdown to HTML and create artifact
        run: |
          /scripts/deploy.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: artifact.tar
          retention-days: 1
          overwrite: true
