name: Deploy image to the dev environment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      ECR_REGION:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
    secrets:
      ECR_REGISTRY:
        required: true
      ECR_ROLE_TO_ASSUME:
        required: true
      KUBE_CERT:
        required: true
      KUBE_CLUSTER:
        required: true
      KUBE_NAMESPACE:
        required: true
      KUBE_TOKEN:
        required: true


jobs:
  deploy:
    name: Deploy
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Authenticate to the cluster
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
        run: |
          echo "${{ secrets.KUBE_CERT }}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
          kubectl config use-context ${KUBE_CLUSTER}

      - name: Upgrade the Helm chart
        env:
          IMAGE_TAG: ${{ github.sha }}
          REGISTRY: ${{ secrets.ECR_REGISTRY }}
          REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
          HELM_DIR: "helm_deploy/laa-access-civil-legal-aid"
          SHARED_IP_RANGES_LAA: $(cat https://raw.githubusercontent.com/ministryofjustice/laa-ip-allowlist/main/cidrs.txt | sed ':a;N;$!ba;s/\n/,/g;s/,$//')${{ env.SHARED_IP_RANGES_LAA }}
          DEV_HOST: "access-cla.cloud-platform.service.justice.gov.uk"
          # head_ref is set if the workflow was triggered by a PR, ref_name is used if the workflow was trigged by a push.
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          export CLEANED_BRANCH_NAME=$(echo ${BRANCH_NAME} | sed 's/^feature[-/]//' | sed 's:^\w*\/::' | tr -s ' _/[]().' '-' | tr '[:upper:]' '[:lower:]' | cut -c1-28 | sed 's/-$//')
          export HOST_NAME=${CLEANED_BRANCH_NAME}-${DEV_HOST}

          helm upgrade ${CLEANED_BRANCH_NAME} \
          ${HELM_DIR} \
          --namespace=${{ secrets.KUBE_NAMESPACE }} \
          --values ${HELM_DIR}/values/values-${{ inputs.environment }}.yaml \
          --set-string sharedIPRangesLAA=$SHARED_IP_RANGES_LAA \
          --set image.repository=${REGISTRY}/${REPOSITORY} \
          --set image.tag=${IMAGE_TAG} \
          --set fullnameOverride=${CLEANED_BRANCH_NAME} \
          --set ingress.hosts[0].host=${HOST_NAME} \
          --set ingress.tls[0].hosts[0]=${HOST_NAME} \
          --force \
          --install
