name: Publish documentation

on:
  workflow_call:
    secrets:
      github-token:
        description: "GitHub token for downloading artifacts"
        required: true

permissions:
  contents: read     # Needed for downloading artifacts
  pages: write      # Needed for GitHub Pages deployment
  id-token: write   # Needed for deployment authentication

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: github-pages
          path: github-pages
          github-token: ${{ secrets.github-token }}

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
