name: Deploy to a Cloud Platform environment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      ECR_REGION:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
    secrets:
      ECR_REGISTRY:
        required: true
      ECR_ROLE_TO_ASSUME:
        required: true
      KUBE_CERT:
        required: true
      KUBE_CLUSTER:
        required: true
      KUBE_NAMESPACE:
        required: true
      KUBE_TOKEN:
        required: true


jobs:
  deploy:
    name: Deploy
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Authenticate to the cluster
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
        run: |
          echo "${{ secrets.KUBE_CERT }}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
          kubectl config use-context ${KUBE_CLUSTER}
      
      - name: Fetch and set SHARED_IP_RANGES_LAA environment variable
        run: |
          SHARED_IP_RANGES_LAA=$(curl -s https://raw.githubusercontent.com/ministryofjustice/laa-ip-allowlist/main/cidrs.txt | tr -d ' ' | tr '\n' ',' | sed 's/,/\\,/g' | sed 's/\\,$//')
          echo "SHARED_IP_RANGES_LAA=$SHARED_IP_RANGES_LAA" >> $GITHUB_ENV
      
      - name: Upgrade the Helm chart
        env:
          IMAGE_TAG: ${{ github.sha }}
          REGISTRY: ${{ secrets.ECR_REGISTRY }}
          REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
          HELM_DIR: "helm_deploy/laa-access-civil-legal-aid"
          SHARED_IP_RANGES_LAA: ${{ env.SHARED_IP_RANGES_LAA }}
        run: |
          helm upgrade laa-access-civil-legal-aid \
          ${HELM_DIR} \
          --namespace=${{ secrets.KUBE_NAMESPACE }} \
          --values ${HELM_DIR}/values/values-${{ inputs.environment }}.yaml \
          --set image.repository=${REGISTRY}/${REPOSITORY} \
          --set image.tag=${IMAGE_TAG} \
          --set-string sharedIPRangesLAA=$SHARED_IP_RANGES_LAA \
          --force \
          --install
