name: Raise Jira Issue

on:
  pull_request:
    types: [opened, reopened]

jobs:
  gajira:
    name: Raise Jira Issue
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.title, 'snyk') }}
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Process PR data
      id: process_pr_data
      run: |
        repo_name=$(basename ${{ github.repository }})

        pr_body="${{ github.event.pull_request.body }}"
        python -c "
        import html
        import re
        import os

        pr_body = os.getenv('PR_BODY', '')
        clean_body = re.sub(r'<[^>]+>', '', html.unescape(pr_body))
        print(f'::set-output name=clean_body::{clean_body}')
                  "
        echo "repo_name=$repo_name" >> $GITHUB_ENV
        echo "stripped_body='$clean_body'" >> $GITHUB_ENV

    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
          project: LGA
          issuetype: Task
          summary: "[Snyk] -  ${{ env.repo_name }} -  ${{ github.event.pull_request.title }}"
          description: ${{ env.stripped_body }}