name: Release

run-name: ${{ github.ref_name }}

on:
  push:
    branches:
      - main

jobs:
  static-analysis:
    name: Static Analysis
    uses: ./.github/workflows/static-analysis.yml

  build-and-push:
    name: Build
    uses: ./.github/workflows/build-and-push.yml
    needs: linting-and-formatting
    with:
      ECR_REGION: ${{vars.ECR_REGION}}
      ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}

  deploy-staging:
    name: Staging
    uses: ./.github/workflows/deploy.yml
    if: github.ref == 'refs/heads/master'
    needs: build-and-push
    with:
      environment: staging
      ECR_REGION: ${{vars.ECR_REGION}}
      ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

  deploy-production:
    name: Production
    uses: ./.github/workflows/deploy.yml
    if: github.ref == 'refs/heads/master'
    needs: deploy-staging
    with:
      environment: production
      ECR_REGION: ${{vars.ECR_REGION}}
      ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
