name: Security

on: workflow_call

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Adjust permissions
        # Fix permissions for the working directory
        run: sudo chmod -R 777 $(pwd)

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
        target: 'http://your-app-url.com'
        zap-opts: '-config api.disablekey=true -config dirs.workDir=/zap/wrk'
        rules-file: '.github/zap-rules.tsv'
        report-dir: 'zap-reports'
        continue-on-error: true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
            name: zap-report
            path: zap-reports/zap_report.html