name: Security

on: workflow_call

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download HOST_NAME artifact
      uses: actions/download-artifact@v4
      with:
        name: host-name

    - name: Use HOST_NAME
      run: echo "The hostname is ${{ env.HOST_NAME }}"

    - name: ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        target: ${{ env.HOST_NAME }}
        artifact_name: 'zap_report'
      continue-on-error: true

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap_report
        path: 'report_html.html'