name: Security

on: workflow_call

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        target: 'https://security-pipeline-access-cla.cloud-platform.service.justice.gov.uk/'
        artifact_name: 'zap_report'
      continue-on-error: true

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap_report
        path: 'report_html.html'