name: Snyk scan

on:
  workflow_call:
    inputs:
      image_uri:
        description: "URI of an already pushed image to scan. Leave unset to skip container scanning"
        required: false
        type: string
      exclude_base_image_vulns:
        description: "Exclude vulnerabilities inherited from the base image"
        required: false
        default: false
        type: boolean
    secrets:
      SNYK_CLIENT_ID:
        required: true
      SNYK_CLIENT_SECRET:
        required: true
      ACCESS_ECR_ROLE_TO_ASSUME:
        required: false

jobs:
  sast:
    name: Snyk SAST scan
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/sast.yml@3b61534ec28baab6171267eb56187bb597e89d45
    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read
    with:
      image_uri: ${{ inputs.image_uri }}
      dockerfile_path: Dockerfile
      exclude_base_image_vulns: ${{ inputs.exclude_base_image_vulns }}
    secrets:
      SNYK_CLIENT_ID: ${{ secrets.SNYK_CLIENT_ID }}
      SNYK_CLIENT_SECRET: ${{ secrets.SNYK_CLIENT_SECRET }}
      ECR_ROLE_TO_ASSUME: ${{ secrets.ACCESS_ECR_ROLE_TO_ASSUME }}
