name: Snyk image scan

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  snyk-image-scan:
    name: Snyk Docker image scan
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/snyk.yml@main
    with:
      tag: laa-access-civil-legal-aid
      dockerfile_path: Dockerfile
    secrets:
      snyk_token: ${{ secrets.snyk_token }}
