name: Build, Test and Deploy

run-name: Build, Test and Deploy ${{ github.ref_name }}

on: push

jobs:
  linting-and-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: check --output-format=github
          src: './src'

  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      ECR_REGION: ${{vars.ECR_REGION}}
      ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
